#!/bin/bash
#SBATCH --job-name=fcs_clean
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 8
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mem=16G
#SBATCH -o logs/fcs_clean_%A_%a.out
#SBATCH -e logs/fcs_clean_%A_%a.err
# -----------------------------------------------------------------------------
# Clean contamination generated by fcs_adaptor/gx reports
#
# Original assembly is kept as final_assembly.prefcs.fna
# Cleaned assembly is copied into $WORKDIR as final_assembly.fna
#
# Run one sample: sbatch fcs_clean.sh <sample_id>
# Run whole batch: sbatch --array=1-15 fcs_clean.sh
# -----------------------------------------------------------------------------
PIPELINE_DIR="${PIPELINE_DIR:-/path/EAGER_sequences/scripts}"
source "${PIPELINE_DIR}/lib.sh"
pipeline_init "$@"
require_assembly
activate_env "$QC_ENV"

FCS_PY="${CONTAINERS}/fcs.py"
export FCS_DEFAULT_IMAGE="${CONTAINERS}/fcs-gx.sif" # absolute path

command -v singularity &>/dev/null || { echo "singularity not on PATH" >&2; exit 1; }
[[ -f "$FCS_PY" ]] || { echo "missing ${FCS_PY}" >&2; exit 1; }
[[ -f "$FCS_DEFAULT_IMAGE" ]] || { echo "missing ${FCS_DEFAULT_IMAGE}" >&2; exit 1; }

# count to see if any cleaning actions are needed
_actions() { [[ -s "$1" ]] && grep -v '^#' "$1" | grep -cv '^[[:space:]]*$' || echo 0; }

ADAPTOR_REPORT="${WORKDIR}/fcs_adaptor/fcs_adaptor_report.txt"
GX_REPORT="${WORKDIR}/fcs_gx/*fcs_gx_report.txt"

N_ADAPTOR=$(_actions "$ADAPTOR_REPORT")
N_GX=$(_actions "$GX_REPORT")
echo "${SAMPLE_ID} adaptor actions ${N_ADAPTOR}"
echo "${SAMPLE_ID} gx actions ${N_GX}"

if [[ "$N_ADAPTOR" -eq 0 && "$N_GX" -eq 0 ]]; then
    echo "${SAMPLE_ID} nothing to clean."
    exit 0
fi

# assembly backup
PREFCS="${WORKDIR}/final_assembly.prefcs.fna"
if [[ -f "$PREFCS" ]]; then
    echo "pre-clean assembly found, re-cleaning"
else
    cp "$ASSEMBLY" "$PREFCS"
    echo "pre-clean assembly saved $(basename "$PREFCS")"
fi

WORK="${WORKDIR}/.fcs_clean.$$.fna"
cp "$PREFCS" "$WORK"
trap 'rm -f "$WORK"' EXIT

_apply() {
    local label="$1" report="$2" outdir="$3"
    cat "$report"
    local cleaned="${outdir}/clean.fasta"
    cat "$WORK" | python3 "$FCS_PY" clean genome \
        --action-report "$report" \
        --output "$cleaned" \
        --contam-fasta-out "${outdir}/contam.fasta"
    [[ -s "$cleaned" ]] || { echo "${label} - missing or empty output" >&2; exit 1; }
    cp "$cleaned" "$WORK"
}

[[ "$N_ADAPTOR" -gt 0 ]] && _apply adaptor "$ADAPTOR_REPORT" "${WORKDIR}/fcs_adaptor"
[[ "$N_GX" -gt 0 ]] && _apply gx "$GX_REPORT" "$(dirname "$GX_REPORT")"

cp "$WORK" "$ASSEMBLY"

run_info
echo "done ${SAMPLE_ID} - cleaned assembly is now final_assembly.fna"
